### ISSUE TITLE
Does not consider tabindex

### ISSUE THREAD

**Issue by JordanMajd** [joelpurra/plusastab#6]
This plugin does not consider tab indexes as it iterates through data-plus-as-tab elements.

```
<input tabindex=1 data-plus-as-tab="true"/>
<input tabindex=3 data-plus-as-tab="true"/>
<input tabindex=2 data-plus-as-tab="true"/>
```

 - Using the tab key it will go to the first input, then the last input and finally the middle input.
 - Using this plugin it will go to the first input, middle input then the last input.

**Comment by joelpurra** [comment]
@JordanMajd: this issue belongs to the underlying library [emulatetab](https://github.com/joelpurra/emulatetab) rather than plusastab, but I'll explain myself here.

Ignoring `tabindex` is by choice as I don't like them. I've implemented a solution [for skipping fields](https://github.com/joelpurra/skipontab/wiki/SkipOnTab-versus-tabindex) (similar to `tabindex="-1"`) and have thought of implementing your use case (non-linear jumping), but haven't taken the time. Could you create a new project?

There are forks of [emulatetab](https://github.com/joelpurra/emulatetab) which respect tabindex -- you could also look at them.

**Comment by JordanMajd** [comment]
Thank Joel, I'll look into those forks.

I'd love to create a new project, currently I do not have the time.
